name: CI Pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run command
        run: echo "Hello CI/CD"

      - name: build docker image
        run: docker build -t myapp .
